_extends: .github
repository:
  name: github-workflows-core
  description: core functionality for form8ion plugins that manage github workflows
  homepage: https://npm.im/@form8ion/github-workflows-core
  private: false
